export const ART = {
  wood: "art/cards/wood.jpg",
  berries: "art/cards/berries.jpg",
  stone: "art/cards/stone.jpg",
  flint: "art/cards/flint.jpg",
  string: "art/cards/string.jpg",
  villager: "art/cards/villager.jpg",
  armed: "art/cards/armed.jpg",
  spearman: "art/cards/spearman.jpg",
  archer: "art/cards/archer.jpg",
  tree: "art/cards/tree.jpg",
  berrybush: "art/cards/berrybush.jpg",
  rock: "art/cards/rock.jpg",
  towncentre: "art/cards/towncentre.jpg",
  barracks: "art/cards/barracks.jpg",
  spear: "art/cards/spear.jpg",
  bow: "art/cards/bow.jpg",
  wolf: "art/cards/wolf.jpg",
};
